"""人工维护的文件职责与边界，用于生成源码索引；不导入业务模块。

格式：职责 | 文件级输入 | 文件级输出 | 副作用或维护重点。
函数级参数、默认值、返回注解另由 AST 提取，不由本表猜测。
"""

NOTES = {
    "betalens/__init__.py": "公共包入口和部分延迟导出 | import/属性名 | Datafeed、回测及事件研究公共对象 | import betalens 成功不证明全部子模块依赖可用",
    "betalens/datafeed/config.py": "分层配置和缓存 | 运行参数、环境变量、配置文件 | 数据库/日志配置字典 | save 可写配置；不要输出密码",
    "betalens/datafeed/core.py": "研究取数门面与交易日历 | 逻辑表、代码、时间、指标 | DataFrame、交易日列表或成分集合 | Datafeed 构造即获取数据库连接；使用 close/context manager",
    "betalens/datafeed/pool.py": "线程安全只读连接池 | 数据库配置、连接数和超时 | 借出的连接/上下文 | 有连接和全局池生命周期；不能用于入库",
    "betalens/datafeed/query.py": "参数化查询与新旧结构路由 | cursor、逻辑表、时间范围和指标 | 查询长表、宽表、日期/状态 | 读取 PostgreSQL；nearest 与 in-range 的区间语义要保持",
    "betalens/datafeed/registry.py": "读层逻辑数据集与核心指标映射 | 数据集名、指标名 | DatasetSpec/CoreMetric | 与写层 registry 和兼容视图保持一致",
    "betalens/datafeed/universe.py": "历史指数成分查询 | cursor、指数代码、历史日期 | 集合、有效日期、date→set 面板 | PIT 快照读取；不能拿最新成分填全历史",
    "betalens/datafeed/industry.py": "历史行业归属查询 | cursor、证券、时点、分类体系 | 行业记录或成员列表 | 有数据库读取与新旧 schema 分支",
    "betalens/datafeed/validation.py": "数据缺失、日期、重复检查修复 | DataFrame、字段、FillStrategy | 检查结果或修复后的表 | 修复策略可能改变样本，不能无条件填零",
    "betalens/factor/config.py": "完整 YAML 校验和参数映射 | YAML 路径、配置分节 | FactorSpec kwargs、run kwargs、绝对输出路径 | write_yaml_config 写文件；路径相对 YAML 目录",
    "betalens/factor/factor.py": "可交易池、单/双/多特征分组与权重 | 查询日期/因子长表/标签/分组参数 | 股票池、带标签 MultiIndex 表、权重宽表 | 部分函数查库，分组和权重可离线；标签与同值规则是契约",
    "betalens/factor/preprocessing.py": "去极值、标准化与中性化 | Series/因子长表、行业、市值 | 因子残差、处理表、诊断 | 行业自动查询路径读库；样本不足可能 skipped",
    "betalens/factor/profiling.py": "因子值体检与跨因子比较 | 因子宽/长表或多因子字典 | 覆盖、分布、自相关、重合度等结果 | 因子体检不等同未来收益评价",
    "betalens/factor/stats.py": "IC、截面与择时统计及图形 | 因子/收益面板、评估参数 | Series、统计字典、回归/图形/报告 | 调用者负责未来收益对齐；导出路径写文件",
    "betalens/factor/signal.py": "择时信号到目标权重转换 | 因子序列/宽表、阈值与历史规则 | SignalWeightResult：weights、factor_values、events | 起始日期解析可查库；历史窗口不能用未来观测",
    "betalens/factor/mining.py": "参数挖掘调度和窗口评价 | parameter_space.yaml、performance.yaml、MiningSpec hook | MiningResult 和逐因子结果 | 查库、进程/线程、缓存、日志和产物；先限制搜索范围",
    "betalens/factor/mining_cache.py": "不可变行情缓存发布和切片 | DataFrame/PIT、缓存目录、请求指纹 | manifest、NPY/memmap 与切片 | 读写缓存；过期输入不能因路径相同而复用",
    "betalens/factor/mining_optuna.py": "采样器、范围扩展与扰动适配 | 参数定义、已有评价、搜索设定 | study、参数候选、grid/扰动计划 | 可选 Optuna 依赖；采样并不证明样本外有效",
    "betalens/factor/mining_audit.py": "搜索结果持久化与人可读审计 | 候选、窗口表现、元数据 | SQLite、metadata YAML、Excel 和热力图 | 写文件；指纹、失败状态和全候选记录属于结果的一部分",
    "betalens/backtest/backtest.py": "权重到实际持仓、损益与净值 | 权重矩阵、资金、价格/状态或预载面板 | 实例属性 nav、actual_weight、position、rebalance_log 等 | 构造即执行回测；默认查库；dump 写 Excel",
    "betalens/analyst/metrics.py": "纯绩效指标和收益明细计算 | nav/returns/weight/持仓/交易日志 | 标量、Series、DataFrame 或字典 | 纯计算；年化频率、回撤符号和净值分母需核对",
    "betalens/analyst/analyst.py": "评价门面及报告导出 | 回测实例/净值/Excel、可选基准 | Analyst、汇总表、Excel/HTML 报告 | 基准代码可触发查库，报告会写文件；完整依赖需另验收",
    "betalens/analyst/plotting.py": "静态和交互图形 | 净值、指标、权重及损益表 | matplotlib/Plotly 对象、图片字节、HTML 片段 | 图形依赖；保持坐标、单位与空值语义",
    "betalens/analyst/naming.py": "证券代码名称映射和缓存 | 证券代码集合 | 名称字典/标签/重命名表 | 尝试查库，失败回退代码；缓存可能需清理",
    "betalens/eventstudy/eventstudy.py": "标准交易日事件窗口研究 | Datafeed、事件 Series、代码与窗口 | 价格/收益矩阵、统计、比较结果和图形 | 查行情与日历；Day 0、重叠和缺失不可压缩错位",
    "betalens/robust/robust.py": "当前公开导出的 RobustTest 与旧辅助工具 | fund Series、factor DataFrame、重采样次数 | OX、t统计、修正概率等 | 滞后一期、联合删缺失和线程重采样；旧 work 入口需审查",
    "betalens/robust/newrobust.py": "另一版 Lucky Factors 实现 | 见本文件 RobustTest 签名 | 本实现的检验对象及结果 | 包 __init__ 未导出这一版本，不能按文件名认定已替换旧版",
    "betalens_db_manager/__main__.py": "CLI/桌面启动分发 | 命令行、配置与确认选项 | 计划/运行 JSON、退出状态或 GUI | init/import 可写库；无参数启动桌面界面",
    "betalens_db_manager/manager.py": "无 Qt 的数据库服务门面 | 配置/profile、查询、迁移/导入请求 | 统一的状态、计划、查询和运行报告 | 构造服务与本地 JobStore；按调用读写 DB/文件",
    "betalens_db_manager/db.py": "管理端连接和分页查询 | QueryRequest、数据库配置 | 查询记录、连接信息、分页 token | 短连接 PostgreSQL；表名白名单与参数化必须保留",
    "betalens_db_manager/schema.py": "版本化建库迁移和核验 | 配置、目标版本、migration 资源 | plan/init/verify 报告 | 建库、DDL、校验和检查；不能直接改已应用 migration",
    "betalens_db_manager/contracts.py": "每版结构契约 | schema 版本 | SchemaContract：表列索引等 | 与 SQL migration 和 verify 同步",
    "betalens_db_manager/registry.py": "管理端逻辑数据集、指标与可写性 | 表名/指标别名/写入要求 | DatasetSpec/CoreMetric 或异常 | 与读层 registry 同步；不要用任意表名绕过注册",
    "betalens_db_manager/constants.py": "导入列、模式、日志路径等常量 | 模块导入 | DB_COLUMNS、默认限制和模式名 | 标准必需五列加可选 remark；不是所有接口都有 unit 列",
    "betalens_db_manager/profiles.py": "连接档案选择与来源解释 | 用户 profile、覆盖配置、会话密码 | ResolvedConnection 和显示配置 | 档案写盘不保存密码；effective 配置仍可能含密码",
    "betalens_db_manager/import_adapters.py": "带目标类型的源数据适配注册 | adapter 名、源文件、目标表、options | ImportBatch 子类型及拒绝行 | 读取文件、校验与时间对齐；注册后才能参与统一导入",
    "betalens_db_manager/importers.py": "旧导入接口兼容与数据库写入器 | 标准表/批次、目标、写入模式/DeleteRequest | dry-run、写入或删除统计 | 临时 staging、COPY、事务和分区；负责实际写库",
    "betalens_db_manager/validators.py": "导入前数据校验 | 规范化 DataFrame 和允许选项 | ValidationReport | 不应把被拒绝行悄悄视作成功导入",
    "betalens_db_manager/jobs.py": "单文件导入任务编排 | 路径、目标、adapter、preview token、取消回调 | 任务记录和进度 | SHA256/预览一致性、写库、日志和拒绝行文件；文件级事务",
    "betalens_db_manager/import_manifest.py": "多文件清单预检与恢复 | manifest YAML、默认值、检查点 | ManifestPlan、逐文件运行结果 | 批量读写与检查点；整份清单不是单一事务",
    "betalens_db_manager/job_store.py": "本地 SQLite 任务持久化 | 任务/事件/检查点记录 | 历史查询和恢复数据 | 创建/更新本地 SQLite；不同于行情 PostgreSQL",
    "betalens_db_manager/records.py": "导入记录兼容门面 | 旧记录接口调用、JobStore | 记录和日志路径 | 包装新存储，不要再建一套任务数据库",
    "betalens_db_manager/gui_controller.py": "无 Qt 的界面业务控制 | 用户连接草稿、文件计划、操作请求 | 服务结果与可执行计划 | 防并发操作与失效预览；便于脱离 GUI 测试",
    "betalens_db_manager/gui_app.py": "PySide6 四页桌面界面 | 用户动作、controller 结果 | 表格、对话框、进度、窗口 | Qt 主线程与后台 worker 通信；不得阻塞 UI",
    "betalens_db_manager/gui.py": "GUI 公共兼容启动入口 | 启动调用 | 桌面 main 导出 | UI 实现主要在 gui_app.py",
    "betalens_db_manager/utils.py": "路径、哈希、JSON 和表格预览工具 | 路径/配置/对象/DataFrame | 可序列化对象、摘要与路径 | 哈希读取文件，ensure_parent 创建目录",
    "betalens_db_manager/adapters/files.py": "CSV/Excel 读取、分块与时间对齐 | 源路径、编码、读取选项 | DataFrame/迭代批次 | 文件 I/O；不能从依赖 pyarrow 推定此入口支持 Parquet",
    "betalens_db_manager/adapters/ede.py": "Wind EDE 宽表解析 | 文件、列元信息、日期规则 | 规范化指标长表 | 文件读取；区分报告期和可得日期",
    "betalens_db_manager/adapters/industry.py": "行业源数据规范化 | 行业成员数据与分类选项 | 行业长表记录 | 生效日期与分类体系必须保留",
    "betalens_db_manager/adapters/wind.py": "可选 WindPy 行情获取 | 代码、日期、指标选项 | 规范化行情表 | 调用外部 Wind 服务；不是通用离线测试路径",
    "dashboard/backend/main.py": "HTTP 路由、错误码与日志流 | HTTP 路径/查询/请求体 | JSON、SSE、FileResponse | 调服务后可能启动任务或写产物；health 不检查 DB",
    "dashboard/backend/schemas.py": "Pydantic 请求响应模型 | JSON 字段 | 类型化模型或校验错误 | parameters 是开放字典，深层语义还需业务校验",
    "dashboard/backend/factors.py": "YAML 因子发现、详情与动态加载 | 类名/因子名、仓库目录 | FactorSummary/Detail、配置、模块 | 扫描文件/缓存；import 因子脚本必须无回测副作用",
    "dashboard/backend/runs.py": "内存任务队列与执行状态机 | RunRequest、run_id | DashboardRun、RunState、结果/分页 | 单执行线程与独立 dump 线程；写配置产物；clear 不会强杀运行线程",
    "dashboard/backend/serialization.py": "研究对象到前端契约 | 回测/Analyst/因子值、分页参数 | JSON、图表记录、Parquet 和下载状态 | NaN、时间戳、列名、分页筛选须与 TS 对齐",
    "dashboard/backend/eventstudy_dashboard.py": "事件文件发现与事件结果适配 | EventStudyRequest/事件文件 | 事件预览、统计和对比 JSON | 校验文件路径、读文件及查库；独立于因子回测队列入口",
    "dashboard/frontend/src/main.tsx": "React DOM 挂载 | HTML root 元素 | App 渲染 | 浏览器入口",
    "dashboard/frontend/src/App.tsx": "页面、参数表单、轮询日志与结果展示 | API 数据、用户操作、React 状态 | 页面/图表/任务请求 | 单文件多组件；修改状态生命周期要清理订阅/轮询",
    "dashboard/frontend/src/api.ts": "HTTP 客户端、参数编码与重试 | 表单参数、run_id、筛选 | Promise<响应类型> 或 Error | 网络请求；当前重试包含 POST，注意重复创建任务",
    "dashboard/frontend/src/types.ts": "前端数据契约 | 类型声明与后端字段约定 | TS 类型约束 | 编译期类型不能验证运行时 JSON，后端变更需同步",
    "dashboard/frontend/src/PlotView.tsx": "Plotly React 图表包装 | data、layout、config props | 图表组件 | 图形渲染和 resize；由 App 懒加载",
    "dashboard/frontend/src/plotly.d.ts": "Plotly 模块类型声明 | TypeScript 编译 | 类型解析 | 不是运行时代码",
    "dashboard/frontend/src/styles.css": "界面布局和视觉样式 | DOM 类名/状态/视口 | CSS 样式 | 类名与 App JSX 对齐",
    "dashboard/frontend/vite.config.ts": "Vite、API 代理与后端启动插件 | 环境变量、Python 路径、开发服务 | Vite 配置及开发后端进程 | 前端启动可能自动启动 Uvicorn；不是单纯静态配置",
    "betalens-factor/factor_template.py": "通用截面研究管线与中间数据转换 | FactorSpec、运行日期和参数 | RunResult、回测/报告/体检等产物 | 查库、预热/PIT、分组、执行与导出；研究口径中心",
    "betalens-factor/alpha101/alpha101_formulas.py": "101 个公式、依赖与回看需求注册 | alpha 编号、宽表、参数 | 因子宽表/定义/历史需求 | 公式真源；核对 rank 轴、运算单位与累计回看",
    "betalens-factor/alpha101/alpha101_parameters.py": "Alpha 参数空间推导 | 公式参数、生成边界规则 | 各因子搜索定义 | 参数范围不代表统计最优；与公式签名同步",
    "betalens-factor/alpha101/alpha101_mining.py": "Alpha101 的挖掘 hook | 候选参数 | MiningSpec/计算函数配置 | 桥接通用挖掘和公式库",
    "betalens-factor/alpha101/factor_template_alpha101.py": "Alpha 算子与截面/择时模板桥接 | 宽表、窗口、FactorSpec | 算子结果与 RunResult | rank 是截面，ts_rank 是时序；择时仍需截面上下文",
    "betalens-factor/tdx/factor_template_tdx.py": "通达信公式算子及管线适配 | 日频宽表和算子参数 | 技术指标/因子与运行结果 | 平滑/窗口定义不能随意替换为近似函数",
    "betalens-factor/LiqDemand/factor_template_liqdemand.py": "流动性需求因子公共算子和管线 | 行情与类别参数 | 指标与运行结果 | 与 DISP 和类级默认配置一起阅读",
    "betalens-factor/tools/eventstudy/run_eventstudy.py": "事件研究 CLI | 事件 YAML、文件与运行参数 | 事件分析与导出产物 | 文件读取、数据库查询和结果导出",
    ".github/workflows/publish.yml": "发布 release 后构建并发布 PyPI | GitHub release.published | wheel/sdist 与 PyPI 上传 | 外部发布；当前工作流没有测试步骤",
    "pyproject.toml": "包元数据、依赖与构建配置 | pip/build | 安装包与 extras | full 不含 test/docs；因子目录不随包发现安装",
    "dashboard/frontend/package.json": "前端依赖与 npm 脚本 | npm 命令 | dev/build/preview | 没有声明 npm test 或 lint 脚本",
    "docs/conf.py": "Sphinx 文档构建配置 | Sphinx 与项目 import | HTML 文档构建设置 | 构建可能触发 autodoc 导入",
    "betalens-factor/LiqDemand/DISP/mining/run.py": "DISP 挖掘命令入口 | 同目录搜索和性能 YAML/命令参数 | 通用挖掘结果与输出目录 | 会运行搜索、查库和写产物；先阅读参数范围",
    "betalens-factor/alpha101/mining/run.py": "Alpha101 挖掘命令入口 | 搜索/性能 YAML 与命令参数 | MiningResult 和搜索产物 | 可一次启动多个因子；不可将默认范围当快速冒烟测试",
    "betalens/datafeed/config.example.json": "本地连接配置模板 | 人工填写数据库及日志选项 | 配置管理器读取的字典 | 不是已生效凭据；复制前检查已有配置",
    "dashboard/backend/requirements.txt": "后端依赖声明 | pip install -r | 后端 Python 依赖环境 | 与 pyproject extras 核对版本，安装会改变环境",
    "dashboard/frontend/tsconfig.json": "前端 TypeScript 编译选项 | TS/TSX 源文件 | 类型检查和编译配置 | 改严格性或目标会影响 build",
    "dashboard/frontend/tsconfig.node.json": "Node/Vite 侧 TypeScript 配置 | Vite 等配置源码 | Node 侧编译检查选项 | 与浏览器 tsconfig 职责不同",
    "docs/requirements.txt": "文档构建依赖 | pip install -r | Sphinx 工具环境 | full extras 不等于 docs extras",
    "requirements.txt": "仓库 Python 依赖清单 | pip install -r | 开发/研究环境依赖 | 与 pyproject.toml 对照，不能仅凭文件名认定完全锁定版本",
}

MIGRATIONS = {
    "0001_bootstrap.sql": "创建 schema、迁移记录和基础覆盖元数据",
    "0002_dimensions.sql": "创建证券、名称历史和指标维度",
    "0003_market_fact.sql": "创建日行情事实表与指标存储相关结构",
    "0004_observation_fact.sql": "创建按可得时间组织的通用观测事实表",
    "0005_pit_and_metadata.sql": "创建行业、指数成分、交易状态等 PIT 结构",
    "0006_migrate_legacy.sql": "将旧结构长表迁移进规范化结构",
    "0007_compatibility_views.sql": "保存旧关系并建立兼容视图",
    "0008_finalize.sql": "初始化覆盖信息并完成迁移收尾",
    "0009_lifecycle_audit.sql": "完善生命周期、名称历史及审计相关结构",
    "0010_trade_calendar.sql": "增加按交易所和日期存储的交易日历",
}
